CheckInfo={
    "Common":{"robot":"robot.txt",
              "git":".git/config",
              "svn":".svn/entries",
              "www":["www.zip","www.rar","www.7z","www.tar","www.tar.gz","www.bz2"],
              "editor":[".viminfo","DS_Store"],
              "txt":".txt"
              },
    "file":{
        "php":[".php~",".php.bak",".php.swp",".php.swo","..php.swp","..php.swo"]
    }
}